### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Murks08** [jayacotton/inettools-z80#11]
How about a .cfg file with the time zone. This can either be created by TIMEZONE.COM or by hand / ED.
That (.cfg File) probably won't change anymore.
When I commented on the time zones beyond the Greenwich Equator, I was concerned with the display  "UTC+zone time" or "UTC-zone time". So far, "-" is always displayed.
Something like this:
int zone_off;

void main (int argc, char * argv [])
{
char *out_str;
zone_off = atoi (argv [1]);
out_str = (zone_off> = 0) ? "You set UTC+%d\n": "You set UTC%d\n";
printf (out_str, zone_off);
SetTZ (zone_off);
}

Half or quarter hour deviations are of course not taken into account.

**Comment by jayacotton** [comment]
TIMEZONE takes seconds.  For me that is 25200  (-7hrs)
If you are -3.5 hrs 12600.  So fractional hrs are handled.

I think I have a problem with the sign bit.  I will work on that part today.

**Comment by jayacotton** [comment]
From this table of time zones, you can see that there +/- 30 or 45 minute zones.
No fifteens ...
https://www.timeanddate.com/time/zones/

**Comment by jayacotton** [comment]
So, I have updated TIMEZONE NTP DATE and TODAY to work with +/- time zones.  This should
work every where now.  Only problem left is that you have to compute the timezone offset 
by hand.
