### ISSUE TITLE
Inet tools may be interfering with submit on CP/M

### ISSUE THREAD

**Issue by jayacotton** [jayacotton/inettools-z80#13]
So, submit loads itself high in memory.  
Inet tools are compiled with default stack, and temporary storage, heap etc.

It looks like the stack for inet tools is stomping on the submit program.

reported by wayne

**Comment by jayacotton** [comment]
This looks like it my be the solution
#pragma output REGISTER_SP           = 0xd000    // place stack at $d000 at startup

**Comment by wwarthen** [comment]
Unfortunately, I really don't know how submit is working.  I assume it is putting some kind of code stub in high memory and I would assume it locates itself as high as it can (right under BDOS).  The exact location would presumably change depending on the OS memory configuration.  I would think $D000 is safe for SP.  Is that the location you are proposing or the location that is already being used?

**Comment by jayacotton** [comment]
Looks like there is a large difference in the size of SUBMIT .

jay@jay-Ultra-27:~/projects/romwbw/RomWBW$ ls -l ./Source/Images/d_cpm3/u0/SUBMIT.COM
-rw-rw-r-- 1 jay jay 5376 Apr 22 20:15 ./Source/Images/d_cpm3/u0/SUBMIT.COM
jay@jay-Ultra-27:~/projects/romwbw/RomWBW$ ls -l ./Source/Images/d_cpm22/u0/SUBMIT.COM
-rw-rw-r-- 1 jay jay 1280 May 15 17:38 ./Source/Images/d_cpm22/u0/SUBMIT.COM

**Comment by wwarthen** [comment]
Yes, the CP/M 3 SUBMIT is entirely different from the CP/M 2.2 SUBMIT.  I'm not sure that explains the corruption issue though.

**Comment by jayacotton** [comment]
I am testing code now with the stack moved down to c000.

**Comment by jayacotton** [comment]
This bug is restricted to CPM3.  I don't see problems on CPM 2.2 .

I notice that the CPM3 version of SUBMIT is very much larger than the CPM2.2 version.  I suspect that the size of the code is the issue.  I have modified several of the tools to use a stack value of 0xc000 in the hopes that I can dodge the bug.  But that is not working, now moving on the the hard work of figuring out how the bug asserts.

**Comment by jayacotton** [comment]
One thing I have found is DON'T CAST return variables when using z88dk.

 unsigned int len;

extern unsigned long recv();

len = recv(bla, bla, bla);
or
len = (unsigned int)revc(fla, bla, bla);
^^^ this one seems to make len never reach 0.  which is the exit case for the loop.
Need to spend much more time on this.

**Comment by wwarthen** [comment]
> One thing I have found is DON'T CAST return variables when using z88dk.

That seems like an odd constraint.  Maybe Phillip will have some perspective on this.

**Comment by jayacotton** [comment]
I found that the #pragma output REGISTER_SP = 0x9000 is not really working.  This explains why 
changes to the value never seem to change the outcome....

The stack is reporting at 0xf1b2.  ?? way up there.  

Here is the stack reporting code I put in ifconfig.
unsigned int get_sp()
{
#asm
        ld      hl,0
        add     hl,sp
        ret
#endasm
        return 0;
}

------------
printf("Stack 0x%04x\n",get_sp());
-----------------

output.
A>ifconfig
Stack 0xf1b2
Shift Register SPI Wiznet v1.0
Stack 0xf1b2
inet 192.168.0.172 Stack 0xf1b2
netmask 255.255.255.0
Stack 0xf1b2
Stack 0xf1b2
dns server 192.168.0.1
ether 98.76.b6.11.00.c3


?? Wayne is this even possible ??

**Comment by wwarthen** [comment]
Your code looks right to me.  That seems problematic assuming your CP/M 3
startup looks like this:

CP/M V3.0 Loader
Copyright (C) 1998, Caldera Inc.

 BNKBIOS3 SPR  F700  0700
 BNKBIOS3 SPR  4500  3B00
 RESBDOS3 SPR  F100  0600
 BNKBDOS3 SPR  1700  2E00

 60K TPA

The key number above is the starting address of RESBDOS3 which is F100h.
The stack value appears to be inside the RESBDOS3 address space.

I don't know how the zcc startup code is locating the stack, but it does
not seem right to me.

When you run this on CP/M 2.2, where does it show the stack?  If you create
an "empty" zcc app, does it do the same thing with the stack on CP/M 3?  Is
there any chance that zcc is not considered CP/M 3 compatible?

Surprising this works at all, but would depend on the bit of code that
lives at the address area being corrupted.

-Wayne

**Comment by jayacotton** [comment]
Succeeded in moving the stack for ifconfig.  On CPM3 with ifconfig in the submit file.  Thud!

Still dos not work.  So, the stack does not seem to be the problem.  The symptom is that after
running the submit command, the command processor get weird.

**Comment by wwarthen** [comment]
This is really strange.  Hard to imagine why ifconfig works fine on CP/M
2.2, but not CP/M 3.

I guess you could start ripping stuff out of ifconfig and see when things
improve.  I am sorry I don't have a better suggestion for you.

-Wayne

**Comment by jayacotton** [comment]
I am going to look for unsigned int to signed int conversions with casting .  I suspect that a pointer is being sign extended to fxxx from 8xxx or something like that.  To clarify these could be cast'ed to a pointer somewhere and make a bad address.   As for way this works on cpm2.2  ??? no idea.
Maybe when we catch the bug, it will be clearer what is up.
 This could take a few days.

**Comment by jayacotton** [comment]
BTW:
On my machine, it looks like the TPA calculation is working for finding the stack address....

CP/M V3.0 Loader
Copyright (C) 1998, Caldera Inc.    

 BNKBIOS3 SPR  F800  0600
 BNKBIOS3 SPR  5200  2E00
 RESBDOS3 SPR  F200  0600
 BNKBDOS3 SPR  2400  2E00
 
 60K TPA

**Comment by wwarthen** [comment]
Interesting.  I'm not sure why your RESDOS3 starts 100h higher than mine.
Regardless, that means the stack just needs to be below F200h.  I'm still
not quite sure how to account for the impact of SUBMIT.

-Wayne

**Comment by jayacotton** [comment]
Got a solid lead.
Fresh reboot.
copied in a new version of ifconfig (it uses the TPA calculator )

A>ifconfig
Stack 0xf1b2
Shift Register SPI Wiznet v1.0
Stack 0xf1b2
inet 192.168.0.172 Stack 0xf1b2
netmask 255.255.255.0
Stack 0xf1b2
Stack 0xf1b2
dns server 192.168.0.1
ether 98.76.b6.11.00.c3

A>wizcfg 0 0 192.168.0.120 31100 45

A>ndos3
NDOS3 Started.

A>network j:=c:[0]

A>network k:=d:[0]

A>
A>pip a:=j:rsxls.com

A>rsxls
NDOS3   
LOADER  

A>rsxls l

ADDR NAME     PREV RM BK LD
E106 NDOS3    0007 00 00 00,00,00
EF06 LOADER   E10B 00 00 FF,00,00

HERE is where the problem starts.  I ran ifconfig
again, it reports the stack at 0xf1b2, but notice the address of the ndos3 and the loader.
Its about 200 bytes below Stack 0xf1b2

A>ifconfig
Stack 0xf1b2
Shift Register SPI Wiznet v1.0
Stack 0xf1b2
inet 192.168.0.172 Stack 0xf1b2
netmask 255.255.255.0
Stack 0xf1b2
Stack 0xf1b2
dns server 192.168.0.1
ether 98.76.b6.11.00.c3
A>

After this run of ifconfig.  

A>pip a:=c:rsxrm.com
system hang.

One of the many symptoms of this bug.
I will switch back to the version of ifconfig with the stack at 9000 and see if we still
have this bug, or a different one.

**Comment by wwarthen** [comment]
Yup, ifconfig stack definitely too high with NDOS in this scenario.

**Comment by jayacotton** [comment]
Pushed new code.

**Comment by jayacotton** [comment]
Root cause.  The issue is that the computation for the stack pointer is based on the reported TPA at the time the application starts.  Now in CPM3 there are these rsx modules that are semi perminant.

It looks like the TPA calculator gets confused by these rsx modules.  

The fix is the move the stack way down in memory so that it does not write all over these rsx modules.

The new code seems to be working correctly and the CPM3 system is much more stable than previously.
