### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Murks08** [jayacotton/inettools-z80#8]
Hi Jay,
I think there should also be time zones beyond the Greenwich equator ... GMT + something
Gerd

**Comment by jayacotton** [comment]
I have supplied TIMEZONE.COM, to be used with new copies of NTP.COM
and DATE.COM.

**Comment by jayacotton** [comment]
Gerd, please let me know what results you get with the new code.  Trying
to get it right.

**Comment by jayacotton** [comment]
new thread opened
